nelmio_api_doc:
    documentation:
        info:
            title: Repository browser
            description: Application which search through the source code repositories (ex GitHub)
            version: 1.0.0
    routes:
        path_patterns:
            - ^/api(?!/doc)
